# Generated by Django 4.2.29 on 2026-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller"), ("admin", "Admin")],
                max_length=20,
            ),
        ),
    ]
