# Generated by Django 4.2.29 on 2026-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nid", "National ID"),
                    ("passport", "Passport"),
                    ("license", "Driver License"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="identity_document",
            field=models.FileField(blank=True, null=True, upload_to="kyc_documents/"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("not_submitted", "Not Submitted"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
