# Generated by Django 4.2.29 on 2026-03-10 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("property_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("sale", "Sale"), ("rent", "Rent")],
                        default="sale",
                        max_length=20,
                    ),
                ),
                ("beds", models.IntegerField(blank=True, null=True)),
                ("baths", models.IntegerField(blank=True, null=True)),
                ("area_sqft", models.FloatField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("images", models.JSONField(default=list)),
                ("documents", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PUBLISHED", "Published"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
