# Generated by Django 4.2.29 on 2026-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_options_propertyimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="boundary_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="Polygon coordinates for property boundaries",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="virtual_tour_url",
            field=models.URLField(
                blank=True, help_text="360-degree virtual tour link", null=True
            ),
        ),
    ]
