# Generated by Django 4.2.29 on 2026-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_boundary_coordinates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="airconditioning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="basement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="furnishing_status",
            field=models.CharField(default="unfurnished", max_length=50),
        ),
        migrations.AddField(
            model_name="property",
            name="guestroom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="hotwaterheating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="mainroad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="parking_spaces",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="prefarea",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="stories",
            field=models.IntegerField(default=1),
        ),
    ]
