# Generated by Django 4.2.29 on 2026-03-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_airconditioning_property_basement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="area_anna",
            field=models.FloatField(
                blank=True, help_text="Area in Aana (1 Aana = 342.25 sq ft)", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="area_ropani",
            field=models.FloatField(
                blank=True,
                help_text="Area in Ropani (1 Ropani = 5,476 sq ft)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="district",
            field=models.CharField(
                blank=True, help_text="District name", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="municipality",
            field=models.CharField(
                blank=True,
                help_text="Municipality / VDC name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="ward",
            field=models.CharField(
                blank=True, help_text="Ward number", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House / Ghar"),
                    ("flat", "Flat"),
                    ("bungalow", "Bungalow"),
                    ("apartment", "Apartment"),
                    ("commercial", "Commercial Building"),
                    ("hostel", "Hostel / PG"),
                    ("land", "Land / Jagga"),
                ],
                default="house",
                max_length=50,
            ),
        ),
    ]
