# Generated by Django 4.2.29 on 2026-03-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_area_anna_property_area_ropani_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="available_beds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="bathroom_type",
            field=models.CharField(
                blank=True,
                choices=[("attached", "Attached"), ("shared", "Shared")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="food_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="has_laundry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="has_wifi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="hostel_gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boys", "Boys Only"),
                    ("girls", "Girls Only"),
                    ("mixed", "Mixed / Co-ed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="room_type",
            field=models.CharField(
                blank=True,
                help_text="Single, Double, Triple, etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="workflow_step",
            field=models.IntegerField(default=1),
        ),
    ]
