# Generated by Django 6.0.3 on 2026-03-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_available_beds_property_bathroom_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="documents",
        ),
        migrations.RemoveField(
            model_name="property",
            name="images",
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PUBLISHED", "Published"),
                ],
                default="SUBMITTED",
                max_length=20,
            ),
        ),
    ]
