# Generated by Django 6.0.3 on 2026-03-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0007_remove_property_documents_remove_property_images_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
