# Generated by Django 4.2.29 on 2026-05-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="model_3d_url",
            field=models.URLField(
                blank=True, help_text="3D model GLB/GLTF link", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tour_360_url",
            field=models.URLField(
                blank=True,
                help_text="Alternative 360-degree virtual tour link",
                null=True,
            ),
        ),
    ]
