# Generated by Django 4.2.29 on 2026-03-20 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("legal", "Legal & Documentation"),
                            ("construction", "Construction & Repair"),
                            ("finance", "Financial Services"),
                            ("marketing", "Marketing & Photography"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("icon", models.CharField(default="Settings", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="servicebooking",
            name="service_type",
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="services.service",
            ),
        ),
    ]
