# Generated by Django 4.2.29 on 2026-04-03 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("total_properties", models.IntegerField(default=0)),
                ("total_transactions", models.IntegerField(default=0)),
                ("total_revenue", models.FloatField(default=0.0)),
                ("new_users_today", models.IntegerField(default=0)),
                ("active_fraud_alerts", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PropertyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_id", models.CharField(max_length=255)),
                (
                    "viewer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("viewed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["property_id", "viewer_email"],
                        name="analytics_p_propert_618054_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("action", models.CharField(max_length=100)),
                ("status", models.CharField(default="success", max_length=20)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user_email", "action", "timestamp"],
                        name="analytics_a_user_em_493b00_idx",
                    )
                ],
            },
        ),
    ]
