# Generated by Django 4.2.29 on 2026-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="credit_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_term_months",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
