# Generated by Django 4.2.29 on 2026-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_payment_date_transaction_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="card_brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_on_dark_web",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="has_chip",
            field=models.BooleanField(default=True),
        ),
    ]
