# Generated by Django 4.2.29 on 2026-03-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0003_transaction_card_brand_transaction_card_on_dark_web_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_reference_id",
            field=models.CharField(
                blank=True,
                help_text="Khalti/Bank reference ID",
                max_length=100,
                null=True,
            ),
        ),
    ]
