import { Property } from '@/types/property';

export const MOCK_PROPERTIES: Property[] = [
    {
        id: '1',
        title: 'Modern Luxury Villa in Budhanilkantha',
        description: 'Breathtaking 5-bedroom luxury villa with a private infinity pool overlooking the Kathmandu valley. Featuring imported marble flooring, a modular kitchen, and a spacious landscaped garden. Perfect for those seeking peace and luxury in the outskirts of the city.',
        price: 85000000,
        location: 'Hattigauda, Kathmandu',
        address: 'Hattigauda Heights',
        city: 'Kathmandu',
        district: 'Kathmandu',
        municipality: 'Budhanilkantha Municipality',
        ward: '8',
        type: 'sale',
        category: 'bungalow',
        bedrooms: 5,
        bathrooms: 4,
        area: 4500,
        area_ropani: 0,
        area_anna: 12,
        images: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200',
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1513584684374-8bdb74838a0f?auto=format&fit=crop&q=80&w=800',
        ],
        status: 'available',
        isVerified: true,
        features: ['Swimming Pool', 'Solar Water Heater', 'Modular Kitchen', 'Garden', 'Ample Parking'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        sellerId: 'seller-1',
    },
    {
        id: '2',
        title: 'Skyline Penthouse in Sanepa',
        description: 'Elite 3-bedroom penthouse with a stunning 360-degree view of the Himalayas and the city. High-end finishes, floor-to-ceiling windows, and exclusive access to the building\'s rooftop lounge and gym.',
        price: 45000000,
        location: 'Sanepa Heights, Lalitpur',
        address: 'Sanepa-2',
        city: 'Lalitpur',
        district: 'Lalitpur',
        municipality: 'Lalitpur Metropolitan City',
        ward: '2',
        type: 'sale',
        category: 'flat',
        bedrooms: 3,
        bathrooms: 3,
        area: 2200,
        images: [
            'https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&q=80&w=1200',
            'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800',
        ],
        status: 'available',
        isVerified: true,
        features: ['Gym', '24/7 Security', 'Backup Generator', 'Reserved Parking'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        sellerId: 'seller-2',
    },
    {
        id: '3',
        title: 'Cozy Family House in Lakeside, Pokhara',
        description: 'A beautiful 3-bedroom home situated just 5 minutes walk from Phewa Lake. Excellent location for a vacation home or permanent residence with a quiet neighborhood and great views.',
        price: 32000000,
        location: 'Lakeside-6, Pokhara',
        address: 'Sedi Heights Road',
        city: 'Pokhara',
        district: 'Kaski',
        municipality: 'Pokhara Metropolitan City',
        ward: '6',
        type: 'sale',
        category: 'house',
        bedrooms: 3,
        bathrooms: 2,
        area: 1800,
        area_ropani: 0,
        area_anna: 8,
        images: [
            'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?auto=format&fit=crop&q=80&w=1200',
            'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80&w=800',
        ],
        status: 'available',
        isVerified: false,
        features: ['Mount View', 'Garden', 'Peaceful Location'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        sellerId: 'seller-1',
    },
    {
        id: '4',
        title: 'Commercial Land in New Baneshwor',
        description: 'Rare opportunity to own commercial land in the heart of Kathmandu. Plot is ideally suited for corporate office building or a shopping complex. High traffic area with excellent accessibility.',
        price: 150000000,
        location: 'Madan Bhandari Road, Baneshwor',
        address: 'Opposite Civil Bank',
        city: 'Kathmandu',
        district: 'Kathmandu',
        municipality: 'Kathmandu Metropolitan City',
        ward: '10',
        type: 'sale',
        category: 'land',
        bedrooms: 0,
        bathrooms: 0,
        area: 5000,
        area_ropani: 1,
        area_anna: 0,
        images: [
            'https://images.unsplash.com/photo-1541443131876-44b03de101c5?auto=format&fit=crop&q=80&w=1200',
        ],
        status: 'available',
        isVerified: true,
        features: ['Main Road Access', 'Commercial Zone', 'High Visibility'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        sellerId: 'seller-3',
    },
    {
        id: '5',
        title: 'Affordable Flat for Rent in Balkhu',
        description: 'Spacious 2-bedroom flat with modern kitchen and separate dining area. Located near the main road with easy access to public transport and local markets.',
        price: 25000,
        location: 'Balkhu, Kathmandu',
        address: 'Near TU Gate',
        city: 'Kathmandu',
        district: 'Kathmandu',
        municipality: 'Kathmandu Metropolitan City',
        ward: '14',
        type: 'rent',
        category: 'flat',
        bedrooms: 2,
        bathrooms: 1,
        area: 950,
        images: [
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1200',
        ],
        status: 'available',
        isVerified: false,
        features: ['Water Supply', 'Separate Electricity Meter', 'Kitchen Racks'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        sellerId: 'seller-2',
    },
];
